import Navbar from "@/components/Navbar";
import "./globals.css";
import AuthProvider from "./AuthProvider";

export const metadata = {
  title: "Promptopia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <div className="main">
          <div className="gradient"></div>
        </div>
        <main className="app">
          <Navbar/>
        {children}
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}
